"""Deliverable Engine — agents produce real, usable artifacts.

This is what makes "100 agents working for you" tangible: instead of only
analyzing, an agent drafts something you can actually use — an outreach email,
an SEO plan, landing-page copy, a growth strategy, a business report.

Each deliverable is generated by Claude when a key is configured, and by a
structured template otherwise (clearly marked ``source: "template"``), so the
founder always gets a real artifact. Everything is logged to the live feed.
"""

from __future__ import annotations

from typing import Dict, List, Optional

from ..core import llm
from ..domain.network import AGENTS_BY_ID
from ..store import STORE, Store, now

# Maps an opportunity category to the kind of artifact and the system persona
# Claude (or the template) writes as.
_KIND_BY_CATEGORY: Dict[str, str] = {
    "product": "product_roadmap",
    "seo": "seo_plan",
    "partnership": "outreach_email",
    "automation": "business_report",
    "new_market": "growth_strategy",
    "pricing": "pricing_brief",
}

_PERSONA: Dict[str, str] = {
    "outreach_email": "an expert B2B outreach copywriter",
    "seo_plan": "a senior SEO strategist",
    "landing_copy": "a high-converting landing page copywriter",
    "growth_strategy": "a startup growth lead",
    "product_roadmap": "a pragmatic product manager",
    "pricing_brief": "a SaaS pricing strategist",
    "business_report": "an executive business analyst",
}


def _kinds() -> List[str]:
    return sorted(_PERSONA.keys())


def generate(
    kind: str,
    brief: str,
    agent_id: str = "executive-head",
    opportunity_id: Optional[str] = None,
    store: Store = STORE,
) -> dict:
    """Produce a deliverable of ``kind`` from a free-text ``brief``."""

    kind = kind if kind in _PERSONA else "business_report"
    spec = AGENTS_BY_ID.get(agent_id)
    agent_name = spec.name if spec else "Executive Core"

    persona = _PERSONA[kind]
    system = (
        f"You are {persona} working inside Titan Omega, an autonomous company OS. "
        "Produce a concise, immediately usable artifact in Markdown. No preamble — "
        "start with the artifact itself. Be specific and actionable."
    )
    prompt = f"Create a {kind.replace('_', ' ')} for the following:\n\n{brief}"

    content = llm.complete(system, prompt, max_tokens=1800)
    source = "ai"
    if content is None:
        content = _template(kind, brief)
        source = "template"

    deliverable = {
        "id": store.new_id("deliv"),
        "title": _title(kind, brief),
        "kind": kind,
        "agent_id": agent_id,
        "agent_name": agent_name,
        "opportunity_id": opportunity_id,
        "content": content,
        "source": source,
        "created_at": now(),
    }
    store.deliverables[deliverable["id"]] = deliverable
    store.emit(
        agent_id,
        "deliverable",
        f"{agent_name} produced a {kind.replace('_', ' ')} ({source}).",
        "success",
    )
    return deliverable


def from_opportunity(opportunity_id: str, store: Store = STORE) -> dict:
    """Turn an opportunity into a concrete deliverable owned by its source agent."""

    opp = store.opportunities[opportunity_id]  # KeyError handled by the caller
    kind = _KIND_BY_CATEGORY.get(opp.get("category", ""), "business_report")
    brief = (
        f"Opportunity: {opp['title']}\n"
        f"Context: {opp['description']}\n"
        f"Expected revenue: ${opp['expected_revenue']:,.0f}. "
        f"Plan: {'; '.join(opp.get('execution_plan', []))}"
    )
    return generate(
        kind=kind,
        brief=brief,
        agent_id=opp.get("source_agent", "executive-head"),
        opportunity_id=opportunity_id,
        store=store,
    )


def listing(store: Store = STORE) -> List[dict]:
    return sorted(store.deliverables.values(), key=lambda d: d["created_at"], reverse=True)


# --- titles & templates ---------------------------------------------------

def _title(kind: str, brief: str) -> str:
    head = brief.splitlines()[0].replace("Opportunity:", "").strip()
    head = head[:60] + ("…" if len(head) > 60 else "")
    label = kind.replace("_", " ").title()
    return f"{label}: {head}" if head else label


def _template(kind: str, brief: str) -> str:
    """Deterministic fallback so a real artifact exists even with no API key."""

    topic = brief.splitlines()[0].replace("Opportunity:", "").strip() or "the initiative"
    if kind == "outreach_email":
        return (
            f"**Subject:** A quick idea for {topic}\n\n"
            "Hi {{first_name}},\n\n"
            f"I came across your work and think there's a strong fit around {topic}. "
            "We help teams like yours move faster with less manual effort.\n\n"
            "Worth a 15-minute call this week to see if it's relevant?\n\n"
            "Best,\n{{sender_name}}\n\n"
            "_Drafted by the Outreach agent. Connect an ANTHROPIC_API_KEY to generate "
            "fully tailored copy._"
        )
    if kind == "seo_plan":
        return (
            f"## SEO Plan — {topic}\n\n"
            "1. **Keyword cluster** — map 10–15 intent-rich keywords; prioritize "
            "high-impression / low-competition terms.\n"
            "2. **On-page** — rewrite titles, meta, and H1s around the primary cluster.\n"
            "3. **Content** — publish 2 cornerstone pages + 4 supporting articles.\n"
            "4. **Technical** — fix crawl/index gaps; improve Core Web Vitals.\n"
            "5. **Measure** — track rankings + CTR for 4 weeks, then iterate.\n"
        )
    if kind == "landing_copy":
        return (
            f"# {topic}\n\n"
            "**Headline:** Get results without the busywork.\n\n"
            "**Subhead:** Built to save you hours every week.\n\n"
            "- Benefit one\n- Benefit two\n- Benefit three\n\n"
            "**CTA:** Start free →\n"
        )
    if kind == "growth_strategy":
        return (
            f"## Growth Strategy — {topic}\n\n"
            "**North star:** activated users / month.\n\n"
            "- **Acquisition:** double down on the top-converting channel; test 1 new.\n"
            "- **Activation:** remove the biggest onboarding drop-off.\n"
            "- **Retention:** add a re-engagement loop for week-2 churn.\n"
            "- **Revenue:** introduce an annual plan + targeted upsell.\n"
        )
    if kind == "product_roadmap":
        return (
            f"## Product Roadmap — {topic}\n\n"
            "- **Now:** ship the highest-impact fix behind a flag; measure lift.\n"
            "- **Next:** the adjacent feature that compounds the first.\n"
            "- **Later:** expand to the neighbouring use case.\n"
        )
    if kind == "pricing_brief":
        return (
            f"## Pricing Brief — {topic}\n\n"
            "- Model annual-vs-monthly LTV and protect gross margin.\n"
            "- Set an annual discount that lifts cash flow without eroding ARPU.\n"
            "- A/B the new tier on checkout; email monthly subscribers to upgrade.\n"
        )
    return (
        f"## Business Report — {topic}\n\n"
        "**Summary:** Opportunity reviewed and prioritized by the Executive Core.\n\n"
        "**Recommendation:** Proceed with the execution plan; track impact weekly.\n\n"
        f"**Context:**\n\n{brief}\n"
    )
